# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

loglikUPCM <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda) {
    .Call('_UPCM_loglikUPCM', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda)
}

loglikUPCM2 <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda) {
    .Call('_UPCM_loglikUPCM2', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda)
}

loglikUPCM4 <- function(alpha, Y, Q, q, n, I, GHweights, GHnodes, X, cores, betaX, betaU, delta, lambda) {
    .Call('_UPCM_loglikUPCM4', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, GHweights, GHnodes, X, cores, betaX, betaU, delta, lambda)
}

scoreUPCM <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, sigma, lambda) {
    .Call('_UPCM_scoreUPCM', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, sigma, lambda)
}

loglikUGPCM <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda) {
    .Call('_UPCM_loglikUGPCM', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda)
}

loglikUGPCM2 <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda) {
    .Call('_UPCM_loglikUGPCM2', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda)
}

scoreUGPCM <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, sigma, lambda) {
    .Call('_UPCM_scoreUGPCM', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, sigma, lambda)
}

loglikUGPCM4 <- function(alpha, Y, Q, q, n, I, GHweights, GHnodes, X, cores, betaX, betaU, delta, slopes, lambda) {
    .Call('_UPCM_loglikUGPCM4', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, GHweights, GHnodes, X, cores, betaX, betaU, delta, slopes, lambda)
}

loglikUPCMnoX <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda) {
    .Call('_UPCM_loglikUPCMnoX', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda)
}

scoreUPCMnoX <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, cores, sigma, lambda) {
    .Call('_UPCM_scoreUPCMnoX', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, cores, sigma, lambda)
}

loglikUPCM4noX <- function(alpha, Y, Q, q, n, I, GHweights, GHnodes, cores, delta, lambda) {
    .Call('_UPCM_loglikUPCM4noX', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, GHweights, GHnodes, cores, delta, lambda)
}

loglikUPCM2noX <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda) {
    .Call('_UPCM_loglikUPCM2noX', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda)
}

loglikUGPCMnoX <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda) {
    .Call('_UPCM_loglikUGPCMnoX', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda)
}

scoreUGPCMnoX <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, cores, sigma, lambda) {
    .Call('_UPCM_scoreUGPCMnoX', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, cores, sigma, lambda)
}

loglikUGPCM2noX <- function(alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda) {
    .Call('_UPCM_loglikUGPCM2noX', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, pall, GHweights, GHnodes, pX, X, cores, lambda)
}

loglikUGPCM4noX <- function(alpha, Y, Q, q, n, I, GHweights, GHnodes, cores, delta, slopes, lambda) {
    .Call('_UPCM_loglikUGPCM4noX', PACKAGE = 'UPCM', alpha, Y, Q, q, n, I, GHweights, GHnodes, cores, delta, slopes, lambda)
}

